# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: parakeet 0.1.6 ruby lib

Gem::Specification.new do |s|
  s.name = "parakeet".freeze
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Scott Tadman".freeze]
  s.date = "2018-01-29"
  s.description = "Manages flocks of microservices".freeze
  s.email = "tadman@postageapp.com".freeze
  s.executables = ["parakeet".freeze]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/parakeet",
    "config/parakeet.yml.example",
    "lib/parakeet.rb",
    "lib/parakeet/config.rb",
    "lib/parakeet/daemonizer.rb",
    "lib/parakeet/instance.rb",
    "lib/parakeet/manager.rb",
    "lib/parakeet/option_parser.rb",
    "lib/parakeet/support.rb",
    "parakeet.gemspec",
    "test/examples/dummy_instance",
    "test/examples/dummy_instance.config.yml",
    "test/examples/empty.yml",
    "test/examples/parallel.yml",
    "test/test_helper.rb",
    "test/unit/parakeet_config_test.rb",
    "test/unit/parakeet_support_test.rb",
    "test/unit/parakeet_test.rb",
    "tmp/.gitignore"
  ]
  s.homepage = "http://github.com/postageapp/parakeet".freeze
  s.licenses = ["UNLICENSED".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Infrastructure management tool for Ruby/Node.js".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<birling>.freeze, [">= 0.2.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<birling>.freeze, [">= 0.2.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<birling>.freeze, [">= 0.2.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

